### ISSUE TITLE
ActionSectionView.swift is missing from repository

### ISSUE THREAD

**Issue by stevehartwell** [techrisdev/Snap#1]
According to the Xcode project, it is in your Documents folder, outside of the repository.

You may want to move it into your repo before it's lost forever.

**Comment by ShishirPatil** [comment]
@stevehartwell were you able to find a solution for this?

**Comment by stevehartwell** [comment]
It was long ago and now I don't remember.

Better ask @techrisdev

**Comment by techrisdev** [comment]
I haven’t worked on the project for a long time, I will try to find the file

**Comment by techrisdev** [comment]
I removed the option of disabling Actions for now, I do want to work on the project again. I will setup the option again in the future.
